### ISSUE TITLE
`!commands` as a dynamic command list

### ISSUE THREAD

**Issue by Syakyr** [Kelgand/sirbotis#1]
A user can create a `!commands` list on their own. However, as more commands are being added, it would become messy to manage them, especially when you have the habit add and remove commands regularly as your streaming program changes over time.

So, as a proposed solution, a dynamic command list (`!commands` by default) would make things easier for the streamer, mods and viewers/members to see what commands they can use to interact in the channel/chat.

Added features to enhance the experience:
- Have an option for a command not to be listed in `!commands`
- Have an option for the command to be sent as a whisper instead to mitigate spam of potentially long command list

**Comment by Kelgand** [comment]
Added in commit https://github.com/Kelgand/sirbotis/commit/f9ae25ff74d3a3cc0e36e007b3509bbd20b0076f
